### ISSUE TITLE
Issue with "MISP v2" in @site/docs/reference/integrations/misp-v2.md

### ISSUE THREAD

**Issue by cordilus74** [demisto/content-docs#132]
The optional field "from" on the search event integration don't work on MISP 2.4.119

**Comment by glicht** [comment]
Hi @cordilus74, 

Thanks for reporting this. 

From the report is seem like this issue is related with the functionality of the integration. This issue tracker is for documentation issues. If you find an issue with the integration please report via our support channels with all relevant info (product version, logs ...). Also, make sure you are working with our latest content version as we had some fixes for MISP v2 released recently.
