### ISSUE TITLE
"npm run build" breaks local folders

### ISSUE THREAD

**Issue by fvigo** [demisto/content-docs#27]
When running `npm run build` locally, the build function does:
```
"build": "copyfiles -E -V -f docs/doc_imgs/* static/doc_imgs/. && replace 'doc_imgs' '/doc_imgs' docs/* --include='*.md*' && docusaurus build",
```

This has two issues:
1. Replacing the relative links from 'doc_imgs' to '/doc_imgs' in the md files locally changes all the files, so git detects all of them as changed.
2. static/doc_imgs/* gets added to the repo, which are detected as new files by git. This can probably be fixed easily by adding static/doc_imgs to `.gitignore`.

With this issues, if you test the build locally then you need to revert before adding files to staging and committing.

**Comment by glicht** [comment]
Why did we change the behaviour we had? Modifying the md files inplace is bad. 

The pr: https://github.com/demisto/content-docs/pull/18 doesn't provide a clear example to the problem it tries to solve

**Comment by sserrata** [comment]
It was determined that the addition of a trailing slash (such as those contained in Algolia search result links) was causing relative asset paths to reference assets in the wrong location. 

For example, given the following URL (with an added trailing slash):

https://demisto.pan.dev/docs/integration-docs/

...And the following relative asset path: `doc_imgs/example.png` (used somewhere in the page)

...The browser would attempt to load the asset from `https://demisto.pan.dev/docs/integration-docs/doc_imgs/example.png` instead of the correct location: `https://demisto.pan.dev/doc_imgs/example.png`.

The trailing slash was first noticed when following an Algolia search result link (reproducible) but it was also sometimes observed when visiting doc pages directly (currently unable to reproduce this behavior).

A Discord chat with a Docusaurus maintainer validated that updating the link references would be a viable solution to allow assets to render in both GitHub and the static generated site (please see snippet of chat history below).

![Screen Shot 2020-01-06 at 4 09 01 PM](https://user-images.githubusercontent.com/9343811/71852671-eac58280-309e-11ea-9c8e-7a2169a44131.png)

**Comment by glicht** [comment]
What about adding a redirect from urls ending with slash to non-slash? I think netlify supports redirects.

**Comment by sserrata** [comment]
I considered this approach but, AFAIK, `_redirects` doesn't support the removal of trailing slashes. I'll investigate again to be certain.

**Comment by csestito** [comment]
@sserrata that is correct, no support of trailing slashes. If you add the rule it will create an infinite redirect.

**Comment by sserrata** [comment]
To close the loop on this I reached out to Netlify for an answer. Please find the response below:

![Screen Shot 2020-01-07 at 12 10 09 PM](https://user-images.githubusercontent.com/9343811/71917877-b3aaac00-3146-11ea-9bc0-f6c6f447a725.png)

**Comment by glicht** [comment]
What about configuring Algolia to not index with trailing slashes? They might have a configuration for this. Google search brought some results about this. For example: https://github.com/algolia/docsearch-configs/issues/744

**Comment by sserrata** [comment]
I contacted Algolia support to inquire how this might be accomplished or if it's supported. I'll update the thread when I hear back.

I wanted to circle back to the original issues to make sure we're all on the same page:

1. Replacing the relative links from 'doc_imgs' to '/doc_imgs' in the md files locally changes all the files, so git detects all of them as changed.
2. static/doc_imgs/* gets added to the repo, which are detected as new files by git. This can probably be fixed easily by adding static/doc_imgs to .gitignore.
3. Modifying md files in place is bad.

Issue 1 and 2 can be avoided by not running `npm run build` locally. Ideally, in the majority of cases, the development server (`npm run start`) should be sufficient for previewing/testing locally.

Concerning 3, I agree that it's *definitely* bad if we're performing builds locally. IMO, running `npm run build` locally is an optional step, to be used (perhaps) in special cases. Instead, use Netlify's build preview feature to preview a production build.

**Comment by fvigo** [comment]
Since we have a workaround and we can work locally, closing this because it's good for now.
