### ISSUE TITLE
Issue with "Reference Docs" in @site/docs/reference/index.md

### ISSUE THREAD

**Issue by cpayne-panw** [demisto/content-docs#790]
## Describe the problem

* Page: [Reference Docs](https://xsoar.pan.dev/docs/reference/index)
* Source: 
Marketplace content pack has a CISCO Meraki Integration (https://xsoar.pan.dev/marketplace/details/ciscomeraki) that's not listed in the integrations documentation or index.  Is it possible to get this added so it's easily referenced?

## Environment
 - OS: [e.g. Windows]
 - Browser: [e.g. chrome, safari, firefox..]
 - Browser Version:

**Comment by meital-aizen** [comment]
Following my discussion with @ShacharKidor, in order to get examples for the documentation of this integration, we need to run the commands and get some outputs but the instance for CISCO Meraki is missing some items/elements:
* Inventory (in Organization)
* Devices (in Network)
* Clients (in Network)

@RomanRapoport @Tomer-M , can you please assist with adding these?

FYI- @ShahafBenYakir

**Comment by Tomer-M** [comment]
@meirwah - Could you please share the access details for CISCO Meraki instance
